### ISSUE TITLE
Add support for more bouncers besides iptables one

### ISSUE THREAD

**Issue by buanzo** [buanzo/crowdsec-plus-console#2]
It would be really useful to include support for other bouncers, such as nginx and cloudflare

**Comment by Tjkent88** [comment]
This should work for you: 

```
- name: installing crowdsec packages
  apt:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
      - crowdsec-cloudflare-bouncer
      - crowdsec-nginx-bouncer
```
